### PR TITLE
Enhance Enforce Dist capabilities to fix, sub optimal bad plans

### PR DESCRIPTION
**Pull request by mustafasrepo**
## Which issue does this PR close?

Closes #.

## Rationale for this change
Current EnforceDistribution rule produces optimal plans, when physical plan at its input is single partitioned plan (E.g physical plan doesn't contain any distribution changing operator). This assumption is valid for datafusion physical optimizer. 

However, others may want to use this rule with their existing plans, that is already distributed. 
In these cases, `EnforceDistribution` used to produce valid plans, generated plans sometimes were not optimal. 

In this PR we extend capabilities of the `EnforceDistribution` rule, so that even if existing plan is already multi-partitioned, physical plan produced by `EnforceDistribution` is still optimal.

## What changes are included in this PR?
The approach to accomplish this as follows.
- Analyze input physical plan to determine requirements at the output of the query (Such has it has single distribution requirement, or it expects output to have `a ASC` ordering etc.). 
- Add an ancillary operator(`GlobalRequiringExec`) so that requirement of the query is not lost across rules.
- In the `EnforceDistribution` rule, ignore-remove any distribution changing operator at its input. 
- Then satisfy distribution requirements of the operators using existing algortihm.

## Are these changes tested?
Yes, new tests are added. To show that intentionally bad, multi-partitioned physical plans can be fixed by `EnforceDistribution` rule.

### CODE REVIEW

**Review by metesynnada — APPROVED** [review]
LGTM.

**Review by ozankabak — APPROVED** [review]
Let's send upstream once we fix the variable namings in the `get_children_exectrees` function.

**Comment by mustafasrepo** [comment]
Upstream [#7671](https://github.com/apache/arrow-datafusion/pull/7671).

**Comment by ozankabak** [comment]
Merged upstream

**Pull request closed without merging**
