### PR TITLE
Named window frames

### PR DESCRIPTION
**Pull request by berkaysynnada**
# Which issue does this PR close?

Closes #6125.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

### CODE REVIEW

**Review by ozankabak — APPROVED** [review]
This looks good to me. Checked in a minor commit removing an unnecessary clone. Next steps:
1. Write a PR body.
2. Get the `sqlparser` counterpart merged.
3. Update Cargo files so that they refer to upstream `sqlparser`.
4. Send upstream.

**Comment by berkaysynnada** [comment]
If the projection is done over a named window, that window name must be defined. Otherwise, it gives an error. This check is removed from parser, and will be added here.

**Comment by mustafasrepo** [comment]
Merged upstream

**Comment by mustafasrepo** [comment]
Merged upstream

**Pull request closed without merging**
